---
title: "Turning Molecules into Data"
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}
{{< include ./_extensions/r-wasm/live/_gradethis.qmd >}}

```{webr}
#| setup: true
#| exercise:
#|  - esol-data
#|  - esol-plot
#|  - esol-load
#|  - esol-experiment

library(readr)

esol <- read_csv("data/esol_clean.csv", show_col_types = FALSE)

```

### From Molecules to Data

Chemists normally think about molecules in terms of structures: atoms connected by bonds forming functional groups and molecular frameworks.

For example, a simple molecule might be represented like this:

CH${_3}$—CH${_2}$—OH

When chemists and pharmaceutical scientists look at this structure, they immediately recognise important features such as:

 - functional groups
 - hydrogen bonding ability
 - polarity
 - molecular size

However, computers cannot interpret chemical structures in the same intuitive way. Instead, we must convert molecules into numerical representations that algorithms can analyse.

This is a central idea in **cheminformatics**, the field that combines chemistry, data science and computational modelling.

In this workshop we'll use the **ESOL dataset**, which we used in Workshop 2, which contains molecular descriptors together with experimentally measured **aqueous solubility**. We'll start with the cleaned version (if you remember, this was what you did in Workshop 2) so will save a bit of time!

### [WebR]{.tag-webr} Loading the cleaned ESOL Dataset

[<strong>ACTIVITY:</strong>]{.highlight-green} Run the code below and from the information generated by the `head` command, identify:

 - Which column represents the number of hydrogen (H) bond donors?
 - Which column represents solubility?

```{webr}
#| exercise: esol-load

library(readr)

esol <- read_csv("data/esol_clean.csv", show_col_types = FALSE)

head(esol)
```

### [WebR]{.tag-webr} Visualising the data

We can explore how molecular descriptors relate to solubility:

```{webr}

#| exercise: esol-plot

library(ggplot2)

ggplot(esol, aes(x = `Number of H-Bond Donors`, y = `measured log solubility in mols per litre`)) +
  geom_point() +
  labs(
    title = "Number of H-Bond Donors vs Solubility",
    x = "Number of H-Bond Donors",
    y = "Measured log Solubility"
  )
```

[<strong>ACTIVITY:</strong>]{.highlight-green} What pattern do you observe? Do molecules with more H-bond donors tend to be more soluble or less soluble? N.B. A more negative log solubility value means that a compound is less soluble in water.

[<strong>EXPERIMENT:</strong>]{.highlight-pink} Modify the code below to plot the solubility vs polar surface area.

```{webr}
#| exercise: esol-experiment

ggplot(esol, aes(x = ____, y = ____)) +
  geom_point()
```

:::: {.hint exercise="esol-experiment"}
::: {.callout-note collapse="false"}
## Hint 1

The name of the relevant column is: `Polar Surface Area`.
:::
::::

::: {.solution exercise="esol-experiment"}
## Fully worked solution

```{webr}
#| exercise: esol-experiment
#| solution: true

ggplot(esol, aes(x = `Polar Surface Area`, y = `measured log solubility in mols per litre`)) +
  geom_point()
```
:::

```{webr}
#| exercise: esol-experiment
#| check: true
gradethis::grade_this_code()
```

Machine learning models cannot see molecular structures directly. Instead, they learn relationships between numerical molecular descriptors and experimental properties.

In the next section we will see how a neural network learns patterns in these descriptors.

### [RStudio]{.tag-rstudio} Save the code

Copy the code below into your own R script for future work:

```r
library(readr)
library(ggplot2)

esol <- read_csv("esol_clean.csv")

head(esol)

ggplot(esol, aes(x = `Number of H-Bond Donors`, y = `measured log solubility in mols per litre`)) +
  geom_point() +
  labs(
    title = "Number of H-Bond Donors vs Solubility",
    x = "Number of H-Bond Donors",
    y = "Measured log Solubility"
  )
```

Remember though... you'll need to have saved the `esol_clean.csv` file (available for you on Canvas/CH4004/Mathematics/Workshop 8). The command `setwd()` is useful if you need to change your working directory (in case you've saved your data in a different folder), or alternatively write the entire folder address in your `read_csv` call.

The next section introduces you to neural networks themselves!
